### ISSUE TITLE
Also install *-dbgsym?

### ISSUE THREAD

**Issue by alama** [Shnatsel/everything-dbg#1]
https://wiki.debian.org/DebugPackage

**Comment by Shnatsel** [comment]
Thanks for pointing that out!

If I'm reading that right, it's OK to try to install both -dbg and -dbgsym packages. Is that correct?

**Comment by Shnatsel** [comment]
Actually, nevermind. I've implemented -dbgsym support in branch [dbgsym](https://github.com/Shnatsel/everything-dbg/tree/dbgsym), I'd appreciate if someone could test it on recent Debian with -dbgsym support.
